// eslint-disable-next-line import/prefer-default-export
export const data = [
  {
    No: 1,
    'Number of vehicle': 'Vehicle 1',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 2,
    'Number of vehicle': 'Vehicle 2',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 3,
    'Number of vehicle': 'Vehicle 3',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 4,
    'Number of vehicle': 'Vehicle 4',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 5,
    'Number of vehicle': 'Vehicle 5',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 6,
    'Number of vehicle': 'Vehicle 6',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 7,
    'Number of vehicle': 'Vehicle 7',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 8,
    'Number of vehicle': 'Vehicle 8',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 9,
    'Number of vehicle': 'Vehicle 9',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 10,
    'Number of vehicle': 'Vehicle 10',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 11,
    'Number of vehicle': 'Vehicle 11',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 12,
    'Number of vehicle': 'Vehicle 12',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 13,
    'Number of vehicle': 'Vehicle 13',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 14,
    'Number of vehicle': 'Vehicle 14',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 15,
    'Number of vehicle': 'Vehicle 15',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 16,
    'Number of vehicle': 'Vehicle 16',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 17,
    'Number of vehicle': 'Vehicle 17',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 18,
    'Number of vehicle': 'Vehicle 18',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 19,
    'Number of vehicle': 'Vehicle 19',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 20,
    'Number of vehicle': 'Vehicle 20',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 21,
    'Number of vehicle': 'Vehicle 21',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 22,
    'Number of vehicle': 'Vehicle 22',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 23,
    'Number of vehicle': 'Vehicle 23',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 24,
    'Number of vehicle': 'Vehicle 24',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 25,
    'Number of vehicle': 'Vehicle 25',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 26,
    'Number of vehicle': 'Vehicle 26',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 27,
    'Number of vehicle': 'Vehicle 27',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 28,
    'Number of vehicle': 'Vehicle 28',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 29,
    'Number of vehicle': 'Vehicle 29',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 30,
    'Number of vehicle': 'Vehicle 30',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 31,
    'Number of vehicle': 'Vehicle 31',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 32,
    'Number of vehicle': 'Vehicle 32',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 33,
    'Number of vehicle': 'Vehicle 33',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 34,
    'Number of vehicle': 'Vehicle 34',
    'Vehicle type': 'Maxi',
    Rented: 'No',
    Available: 'No',
    Maintenance: 'Yes',
    Location: 'Rome',
  },
  {
    No: 35,
    'Number of vehicle': 'Vehicle 35',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
  {
    No: 36,
    'Number of vehicle': 'Vehicle 36',
    'Vehicle type': 'Maxi',
    Rented: 'Yes',
    Available: 'Yes',
    Maintenance: 'No',
    Location: 'Rome',
  },
];
