// eslint-disable-next-line import/prefer-default-export
export const data = [
  { id: 1, customer: 'Johny Lee', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 2, customer: 'Johny Lee', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 3, customer: 'Johny Lee', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 4, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 5, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 6, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 7, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 8, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  { id: 9, customer: 'Bob Brown', duration: '1 hour & 5 min', vehicle: 'Maxi' },
  {
    id: 10,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 11,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 12,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 13,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 14,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 15,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 16,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 17,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 18,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 19,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 20,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 21,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 22,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 23,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 24,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 25,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 26,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 27,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 28,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 29,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 30,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 31,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 32,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 33,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 34,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 35,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 36,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 37,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 38,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 39,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 40,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 41,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 42,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 43,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 44,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 45,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 46,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 47,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 48,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 49,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 50,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 51,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 52,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 53,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 54,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 55,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 56,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 57,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 58,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 59,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
  {
    id: 60,
    customer: 'Bob Brown',
    duration: '1 hour & 5 min',
    vehicle: 'Maxi',
  },
];
